
server:
  port: 8082
spring:
  application:
    name: QuartzSchedule
  datasource:
    url: jdbc:mysql://10.1.92.9:3306/schedule?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: taoqy
    password: password123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: true
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    logSlowSql: true
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.taoqy.entity
  configuration:
    map-underscore-to-camel-case: true
quartz:
  enabled: true

xxl:
  job:
    executor:
      appname: xxl-job-executor-taoqy
      ip: 10.1.92.9
      port: 8182
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      address:
    accessToken:
    admin:
      addresses: http://10.1.92.9:8080/xxl-job-admin
